### ISSUE TITLE
music_prop: argument "sc.eset" not detected

### ISSUE THREAD

**Issue by Matthew-Runyan** [xuranw/MuSiC#111]
When attempting to estimate cell type proportions with this command
`pecEst.prop = music_prop(bulk.mtx = exprs(my_exprs), sc.eset = pec.sce, clusters = "clusters", samples = 'sampleID', select.ct = NULL, verbose = F)`
this error message is produced
`Error in music_basis(sc.sce, non.zero = TRUE, markers = sc.markers, clusters = clusters, : 
argument "sc.sce" is missing, with no default`
Obviously the function is calling music_basis which is not recognizing my single cell experiment object(pec.sce) that I made with seurat. If anyone has encountered this please let me know. I also tested this function with the XinT2Dsce.rds single cell reference and received the same result. `my_exprs` is an expression set of the bulk RNA seq data with samples on column names and genes on the row names. Any suggestions are appreciated.

**Comment by 99fatimagr** [comment]
Hi FrankStarling, how did you resolve this? Thanks, Fatima

**Comment by 99fatimagr** [comment]
For anyone else who runs into this issue: replace 'sc.eset' with 'sc.sce'

**Comment by FrankStarling** [comment]
> For anyone else who runs into this issue: replace 'sc.eset' with 'sc.sce'

yes this is what I did to fix it. It wasn't that obvious to me to switch the input variable name when using a single cell object rather than an expression set object. Also in the vignette they use a single cell expierement without changing sc.eset to sc.sce.
