### ISSUE TITLE
Error in sum(y) : invalid 'type' (S4) of argument

### ISSUE THREAD

**Issue by gevro** [xuranw/MuSiC#128]
Hi,
I'm getting this error: "Error in sum(y) : invalid 'type' (S4) of argument"

I triple checked and all the input data formats and parameters are correct.

This error does not happen with your demo data. It only happens with my data.

Thanks

**Comment by gevro** [comment]
I figured out the issue. I am using on-disk BPCells matrices, and those don't work with MuSiC.

**Comment by flacchy** [comment]
Hi @gevro can I ask how you fix the issue? I am having the same problem here

**Comment by gevro** [comment]
Unfortunately not
