### ISSUE TITLE
About the CIBERSORT used in your paper

### ISSUE THREAD

**Issue by Jeremy-qf** [xuranw/MuSiC#14]
Hi, Xuranw
thanks for your great package.
I just have a question in your paper. Since you have compared CIBERSORT with MuSiC in your paper, what is the signature for the CIBERSORT you used?
Looking forward to your response
Thanks
Fei

**Comment by Jeremy-qf** [comment]
What's more, the package "MuSiC" cannot be installed in Windows system (I tried several times and failed finally), but works well in Linux system. Is that right?

**Comment by xuranw** [comment]
Hi Fei,

Thanks for using MuSiC. CIBERSORT has their own website that will generate signature matrix from single cell reference. 
MuSiC should be working under Windows system. Could you please provide more info on that?

Best,
Xuran

**Comment by Jeremy-qf** [comment]
Hi Xuranw
Thanks for your response. Each time I try to install MuSiC, it appears problems below. Same thing happened in many computers of my friends, and we had to change to linux system finally. Have you successfully installed it in windows before?
Thanks
Best
Fei
[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xuranw** [comment]
Hi Fei,

Sorry, I could not see the image. Yes, I have installed my package on my own computer and my labmates' computers. They are under Windows system.

**Comment by Jeremy-qf** [comment]
Hey, try to open the image now. I just use the code like:

# install devtools if necessary
install.packages('devtools')

# install the MuSiC package
devtools::install_github('xuranw/MuSiC')

# load
library(MuSiC)

Then error happens.

Thanks

Fei

________________________________
发件人: xuranw <notifications@github.com>
发送时间: 2019年2月9日 5:38:53
收件人: xuranw/MuSiC
抄送: QIN, FEI; Author
主题: Re: [xuranw/MuSiC] About the CIBERSORT used in your paper (#14)


Hi Fei,

Sorry, I could not see the image. Yes, I have installed my package on my own computer and my labmates' computers. They are under Windows system.

―

**Comment by ectopicaPKC** [comment]
devtools::install_github('xuranw/MuSiC')
Error in read.dcf(path) : 
  Found continuation line starting '        plyr, ...' at begin of record.

I'm pretty sure that is the error Fei is referring too, as I too just got that error. 

Thanks

**Comment by xuranw** [comment]
Thanks for using MuSiC. Actually I'm not sure what happened.

After searching on Internet, Here is the proposed solution:
library(remotes)
install_url(url="https://github.com/xuranw/MuSiC/archive/master.zip", INSTALL_opt= "--no-multiarch")

Hope that helps.

Best,
Xuran

**Comment by ectopicaPKC** [comment]
Thanks. That fixed the issue.
