### ISSUE TITLE
Pre-processing 

### ISSUE THREAD

**Issue by gouthamatla** [xuranw/MuSiC#23]
Hi,

I would like to know what should be the pre-processing steps to apply on bulk and scRNA data before applying MuSiC. I could not find anywhere in the documentation or in github how the preprocessing is done. It's a bit strange. 

For scRNA, how many cells do you need to perform better ? I have a data from pooled scRNA data i.e I pooled all the cells of similar type 1 and quantified the gene expression, so I have 1 sample per cell type. Does it work with it ?

**Comment by msenosainAB** [comment]
Same here!!

**Comment by dorkyaddy** [comment]
same here!

**Comment by IreneZhong918** [comment]
same here!

**Comment by gouthamatla** [comment]
The new [tutorial ](https://xuranw.github.io/MuSiC/articles/MuSiC.html)section suggests that it needs raw gene counts.
