### ISSUE TITLE
Too few common genes

### ISSUE THREAD

**Issue by ewholling** [xuranw/MuSiC#31]
Hi there,

I'm very interested in using this exciting deconvolution tool for my bulk RNA-seq data, but keep running into the error message from music_prop of too few common genes from three different single cell datasets.

I tried pre-processing each dataset by including only genes found in both datasets using the merge function in R, yet I still receive this message. I don't understand how this can be the case if their gene lists are exactly the same.

Thanks so much in advance.

**Comment by v1nperez** [comment]
Was there a solution? Same issue. Previous versions of MuSiC did not give me this error.

**Comment by DagnyAsta** [comment]
Hello, did you figure out your problem? I am having the same error and can't figure out why. I did the same thing as you, by input only genes which overlap between the single cell data and bulk data.

Thank you in advance,
Dagný
