### ISSUE TITLE
additions to vignette

### ISSUE THREAD

**Issue by daskelly** [xuranw/MuSiC#4]
Thanks for making a great package!

I realized I had to `library(xbioc)` in order to run `music_basis()`. It would be helpful to add this to the vignette.

The vignette loads `IEmarkers.RData` but this does not appear to be available from https://github.com/xuranw/MuSiC/tree/master/vignettes/data. Would it be possible to add it?

**Comment by xuranw** [comment]
Thanks for pointing out this issue!
I have added required code and data.
