### ISSUE TITLE
object 'GSE50244.EMTAB.prop' not found

### ISSUE THREAD

**Issue by RinconFer** [xuranw/MuSiC#40]
Hello,

I am running the tutorial of MuSiC to check that everything runs properly before moving to my own data, but while running the function:
m.prop.GSE50244 = rbind(melt(GSE50244.EMTAB.prop$Est.prop.weighted), 
                        melt(GSE50244.EMTAB.prop$Est.prop.allgene), melt(Est.prop.bseq),
                        melt(data.matrix(Est.prop.cibersort)))

R print the error:
Error in melt(GSE50244.EMTAB.prop$Est.prop.weighted) : 
  object 'GSE50244.EMTAB.prop' not found

I have try to figure it out on my own, for example I found that the link in:
"load(gzcon(url('https://xuranw.github.io/MuSiC/data/GSE50244CIBERSORT.RData')))"
 It is not right (Error 404) and changed it for the one I think could be the right one: 'https://github.com/xuranw/MuSiC/tree/master/vignettes/data/GSE50244CIBERSORT.RData'

I have been looking around trying to find the object  'GSE50244.EMTAB.prop' but I haven't been able.

Thanks for you help,
David

**Comment by mhimanshu11** [comment]
I think its just a typo error.
It should be 'Est.prop.GSE50244'
`m.prop.GSE50244 = rbind(melt(Est.prop.GSE50244$Est.prop.weighted), 
                        melt(Est.prop.GSE50244$Est.prop.allgene))
`

**Comment by RinconFer** [comment]
> I think its just a typo error.
> It should be 'Est.prop.GSE50244'
> `m.prop.GSE50244 = rbind(melt(Est.prop.GSE50244$Est.prop.weighted), melt(Est.prop.GSE50244$Est.prop.allgene)) `

Thank you very much, that worked beautifully.
