### ISSUE TITLE
can't compile MuSiC

### ISSUE THREAD

**Issue by akhst7** [xuranw/MuSiC#5]
Hi, 

Installation failed with a following message;

`Downloading GitHub repo xuranw/MuSiC@master
Skipping 2 packages not available: Biobase, bseqsc
Installing 2 packages: bseqsc, nnls
Installing packages into ‘/Volumes/Documents/Users/akihoji/Library/R/3.x/library’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘bseqsc’ is not available (for R version 3.5.1)`

A culprit of this issue is one of the dependency,  bseqsc.   I tried to install it manually by 

`install_github('hutuqiu/BSeQC')`

but I get a following error;

`Error: HTTP error 404.`

Any workaround for this ?

**Comment by xuranw** [comment]
Hi,

The detailed installation of BSEQ-sc can be found [here](https://shenorrlab.github.io/bseqsc/vignettes/pages/installation.html).
The installation of BSEQ-sc
```r
# install devtools if necessary
install.packages('devtools')

# install bseqsc
devtools::install_github('shenorrlab/bseqsc')

# load
library(bseqsc)
```
Hope this answer helps.

Best,
Xuran

**Comment by akhst7** [comment]
The issue is not installing MuSic but one of dependencies, csSAM.

**Comment by xuranw** [comment]
Hi!
I have published the new version of MuSiC. It get rid of the dependency of BSEQ-sc or csSAM. You can try again if you don't mind.

Best,
Xuran

**Comment by akhst7** [comment]
Thanks !! I will try and let you know
