### ISSUE TITLE
Sparse matrix support in MuSiC 1.0 isn't working

### ISSUE THREAD

**Issue by jaclynbeck-sage** [xuranw/MuSiC#99]
I installed the latest version of MuSiC today and am attempting to run it with a SingleCellExperiment object that has a sparse matrix as the count matrix. When I call `music_prop`, it crashes at the start of the function `music_basis` here: 

``` 
if (non.zero) {
    x <- x[rowSums(counts(x)) > 0, ]
}
```

The issue is with rowSums: **Error in rowSums(x) : 'x' must be an array of at least two dimensions**

counts(x) returns a sparse matrix of class "dgCMatrix". If I run `rowSums(counts(x))` in my console, it is able to handle the function call because it figures out it needs to use Matrix::rowSums. However when calling the `music_prop` / `music_basis` function, it tries to use the base rowSums function instead and throws an error.

**Comment by xuranw** [comment]
I have updated MuSiC. Could you please try again?

**Comment by jaclynbeck-sage** [comment]
It's working! Thank you so much, you're awesome for fixing this so quickly!
